name: Deploy FastAPI App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Create PEM file
      run: |
        echo "${{ secrets.EC2_PEM_FILE }}" > ec2-key.pem
        chmod 400 ec2-key.pem

    - name: Deploy to EC2 via SSH
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Setting Git safe directory..."
          git config --global --add safe.directory /home/ec2-user/FastAPI/fixNow-backEnd || exit
    
          echo "Pulling the latest code from Git..."
          cd /home/ec2-user/FastAPI/fixNow-backEnd || exit
          git pull origin main || exit
    
          echo "Rebuilding and restarting Docker container..."
          sudo docker-compose down || exit
          sudo docker-compose up -d --build || exit
    
          echo "Deployment complete!"
        EOF
