name: Deploy FastAPI App to EC2

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Pulling the latest code from Git..."
          cd /home/ec2-user/FastAPI/fixNow-backEnd || exit
          git pull origin main || exit

          echo "Rebuilding and restarting Docker container..."
          docker-compose down || exit
          docker-compose up -d --build || exit

          echo "Deployment complete!"
        EOF
